### ISSUE TITLE
Minor typo in philosophy page and saying Hi!

### ISSUE THREAD

**Issue by Amrithnath** [simpsoka/kathy-pm-next#1]
Hey Kathy!
I am Amrithnath. Firstly 🎉congratulations 🎉 on your new Job! I have followed your journey on :octocat: and was inspired by videos/talks featuring you on product management. I am a video producer turned software engineer, currently moving towards product management as I love solving problems, learning new things and working with people to make the product better.

Your website is awesome! Loved the philosophy section, great source of knowledge.

PS: You have a typo on this [page](https://www.kathy.pm/philosophy#:~:text=I%20believe%20that%20agile%20should%20always%20have%20a%20little) spelling of because is wrong.
![typo](https://user-images.githubusercontent.com/13913707/127983364-e07fecec-7c1c-4d21-81f3-5833410201d6.png)

PPS: ~Do you know who I can reach out to on GitHub for product improvements related to it? Would love to discuss some ideas with them. I totally understand if you are unable to share that info though.~ Nevermind just found the discussions section!

**Comment by simpsoka** [comment]
Wow, it took me an embarrassingly long time to get to this! Thanks, @Amrithnath! Fixed.
